#define CHUNK_SIZE_X_SHIFT 4
#define CHUNK_SIZE_Z_SHIFT 4
#define CHUNK_SUB_Y_SIZE_SHIFT 4

#define CHUNK_SIZE_X (1 << CHUNK_SIZE_X_SHIFT)
#define CHUNK_SIZE_Z (1 << CHUNK_SIZE_Z_SHIFT)
#define CHUNK_SUB_Y_SIZE (1 << CHUNK_SUB_Y_SIZE_SHIFT)

#define CHUNK_SIZE_X_MASK ((1 << CHUNK_SIZE_X_SHIFT) - 1)
#define CHUNK_SIZE_Z_MASK ((1 << CHUNK_SIZE_Z_SHIFT) - 1)
#define CHUNK_SUB_Y_SIZE_MASK ((1 << CHUNK_SUB_Y_SIZE_SHIFT) - 1)

#define MIN_BLOCK_HEIGHT -64
#define MAX_BLOCK_HEIGHT 320

#define TOTAL_BLOCK_HEIGHT (MAX_BLOCK_HEIGHT - MIN_BLOCK_HEIGHT)
#define TOTAL_CHUNK_SUB_HEIGHT (TOTAL_BLOCK_HEIGHT / CHUNK_SUB_Y_SIZE)
#define NEGTIVE_INDEX_HEIGHT (MIN_BLOCK_HEIGHT / CHUNK_SUB_Y_SIZE)
#define POSITIVE_INDEX_HEIGHT (MAX_BLOCK_HEIGHT / CHUNK_SUB_Y_SIZE)