#define CHUNK_SIZE_X 16
#define CHUNK_SIZE_Z 16
#define CHUNK_SUB_Y_SIZE 16
#define MIN_BLOCK_HEIGHT -64
#define MAX_BLOCK_HEIGHT 320


#define TOTAL_BLOCK_HEIGHT (MAX_BLOCK_HEIGHT - MIN_BLOCK_HEIGHT)
#define TOTAL_CHUNK_SUB_HEIGHT (TOTAL_BLOCK_HEIGHT / CHUNK_SUB_Y_SIZE)
#define NEGTIVE_INDEX_HEIGHT (MIN_BLOCK_HEIGHT / CHUNK_SUB_Y_SIZE)
#define POSITIVE_INDEX_HEIGHT (MAX_BLOCK_HEIGHT / CHUNK_SUB_Y_SIZE)